<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class GenerateControllerAndReactPage extends Command
{
    protected $signature = 'app:generate-controller-and-react-page {path} {controllerName}';

    protected $description = 'Generates a React page and a Laravel controller (local dev only)';

    public function handle()
    {
        if (! App::environment('local')) {
            $this->error('This command is only available in the local environment.');

            return 1;
        }

        $path = trim($this->argument('path'), '/');
        $controllerName = trim($this->argument('controllerName'));

        $segments = explode('/', $path);
        $componentBaseName = end($segments);
        $componentName = "{$componentBaseName}-page";

        // Build controller path
        $controllerPath = app_path('Http/Controllers/' . str_replace('\\', '/', $controllerName) . '.php');
        // Check if controller file already exists BEFORE generating
        if (File::exists($controllerPath)) {
            $this->error("❌ Controller file already exists: {$controllerPath}");

            return 1;
        }

        // Generate Laravel controller
        Artisan::call('make:controller', [
            'name' => $controllerName,
        ]);
        // After calling Artisan::call('make:controller', ...)
        $this->info("Controller created: {$controllerName}");

        // Ensure directory exists
        File::ensureDirectoryExists(dirname($controllerPath));

        // Use full path to inertia component
        $inertiaComponentPath = str_replace('\\', '/', $path) . "/{$componentBaseName}-page";

        // Extract namespace and class
        // Parse controller name into namespace and class
        $controllerParts = explode('/', str_replace('\\', '/', $controllerName));
        $className = array_pop($controllerParts);
        $namespaceSuffix = implode('\\', $controllerParts);

        $namespace = 'App\\Http\\Controllers' . ($namespaceSuffix ? '\\' . $namespaceSuffix : '');

        // Overwrite controller file
        $controllerBoilerplate = <<<PHP
        <?php

        namespace {$namespace};

        use App\Http\Controllers\Controller;
        use Inertia\\Inertia;
        use Inertia\\Response;

        class {$className} extends Controller
        {
            public function __invoke(): Response
            {
                return Inertia::render('{$inertiaComponentPath}');
            }
        }
        PHP;

        File::put($controllerPath, $controllerBoilerplate);
        $this->info("Controller updated with Inertia render: {$inertiaComponentPath}");

        // Generate React page
        $filePath = resource_path("js/pages/{$path}/{$componentBaseName}-page.tsx");

        if (File::exists($filePath)) {
            $this->error("File already exists: {$filePath}");

            return 1;
        }

        File::ensureDirectoryExists(dirname($filePath));

        $reactComponentName = Str::studly($componentName);

        $boilerplate = <<<TSX
        const {$reactComponentName} = () => {
          return (
            <div className="p-4">
              <h1 className="text-xl font-bold">{$reactComponentName}</h1>
              <p>This page was generated by Laravel command.</p>
            </div>
          );
        };

        export default {$reactComponentName};
        TSX;

        File::put($filePath, $boilerplate);
        $this->info("React page created: {$filePath}");

        return 0;
    }
}
