/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "api.user": [],
    "home": [],
    "unauthorized": [],
    "subscription.checkout": [],
    "subscription.start": [],
    "subscription.success": [],
    "subscription.inactive": [],
    "invitation.show": [
        {
            "name": "token",
            "required": true
        }
    ],
    "invitation.accept": [
        {
            "name": "token",
            "required": true
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "admin.settings.profile": [],
    "admin.settings.profile.update": [],
    "admin.settings.profile.destroy": [],
    "admin.settings.password": [],
    "admin.settings.password.update": [],
    "admin.settings.appearance": [],
    "admin.billing-portal": [],
    "admin.subscription.status": [],
    "admin.index": [],
    "admin.team.index": [],
    "super-admin.index": [],
    "super-admin.users.index": [],
    "super-admin.users.create": [],
    "super-admin.users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "super-admin.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "super-admin.roles.index": [],
    "super-admin.roles.create": [],
    "super-admin.roles.edit": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "super-admin.tenants.index": [],
    "super-admin.tenants.suspend": [
        {
            "name": "tenant",
            "required": true,
            "binding": "id"
        }
    ],
    "super-admin.tenants.reactivate": [
        {
            "name": "tenant",
            "required": true,
            "binding": "id"
        }
    ],
    "super-admin.tenants.impersonate": [
        {
            "name": "tenant",
            "required": true,
            "binding": "id"
        }
    ],
    "super-admin.impersonation.stop": [],
    "super-admin.activity-log.index": []
}
}
export {};
