/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "api.user": [],
    "home": [],
    "unauthorized": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "super-admin.settings.profile": [],
    "super-admin.settings.profile.update": [],
    "super-admin.settings.profile.destroy": [],
    "super-admin.settings.password": [],
    "super-admin.settings.password.update": [],
    "super-admin.settings.appearance": [],
    "super-admin.index": [],
    "super-admin.users.index": [],
    "super-admin.users.create": [],
    "super-admin.users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "super-admin.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "super-admin.roles.index": [],
    "super-admin.roles.create": [],
    "super-admin.roles.edit": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "super-admin.activity-log.index": []
}
}
export {};
